branches:
-   main
-   master
-   next
-   next-major
-   +([0-9])?(.{+([0-9]),x}).x
-   name: beta
    prerelease: true
-   name: alpha
    prerelease: true
plugins:
-   semantic-release-gitmoji
-   -   '@semantic-release/exec'
    -   prepareCmd: |
            bash .github/semantic_release/set_version.sh ${nextRelease.version} && \
            poetry build && \
            poetry export -f requirements.txt --ansi --without-hashes --extras all --dev --output requirements/dev.txt && \
            poetry export -f requirements.txt --ansi --without-hashes --extras all --output requirements/prod.txt
-   -   '@semantic-release/git'
    -   assets:
        -   pyproject.toml
        -   semantic_release_test/_version.py
        -   requirements/dev.txt
        -   requirements/prod.txt
        message: |
            🔖 ${nextRelease.version}

            ${nextRelease.notes}
-   -   '@semantic-release/github'
    -   assets:
        -   path: dist/*.whl
        -   path: dist/*.tar.gz
