name: Documentation
on:
    pull_request:
        types: [ opened, synchronize, reopened ]
        paths:
            - "docs/**"

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up Python Environment 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Install Dependencies
                run:  |
                      python -m pip install --upgrade pip tox
            -   name: Set up Python Environment 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Generate Docs
                run:  |
                      tox -e sphinx
            -   name: Commit Changes
                uses: EndBug/add-and-commit@v7
                with:
                    default_author: github_actions
                    message:        "Generate Docs: ${{ github.ref }}"
                    add:            "${{ github.workspace }}/docs/source/api/"
