name: Publish Release

on:
    release:
        types: [ published ]

jobs:
    pypi-publishing:
        runs-on: ubuntu-latest
        env:
            LUNCHMONEY_ACCESS_TOKEN:   ${{ secrets.LUNCHMONEY_ACCESS_TOKEN }}
            SENSITIVE_REQUEST_STRINGS: ${{ secrets.SENSITIVE_REQUEST_STRINGS }}
            SPLITWISE_CONSUMER_KEY:    ${{ secrets.SPLITWISE_CONSUMER_KEY }}
            SPLITWISE_CONSUMER_SECRET: ${{ secrets.SPLITWISE_CONSUMER_SECRET }}
            SPLITWISE_API_KEY:         ${{ secrets.SPLITWISE_API_KEY }}
            PUSHOVER_USER_KEY:         ${{ secrets.PUSHOVER_USER_KEY }}
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up Python Environment 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Install Dependencies
                run:  |
                      python -m pip install --upgrade pip setuptools wheel build twine tox
            -   name: Set up Python Environment 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Run Tests
                run:  |
                      tox -e py39
            -   name: Build Python Package
                run:  |
                      python -m build
            -   name: Publish to PyPI
                run:  |
                      twine upload "${{ github.workspace }}/dist/*" \
                          --username ${{ secrets.PYPI_USERNAME }} \
                          --password ${{ secrets.PYPI_PASSWORD }}
    docker-publishing:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Declare Version Variable
                run:  |
                      VERSION=$(python setup.py --version)
                      echo VERSION=${VERSION} >> ${GITHUB_ENV}
            -   name: Docker Image Building and Publishing
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: juftin/lunchable:latest,juftin/lunchable:${{ env.VERSION }}
