name: Release Drafter

on:
    push:
        branches:
            - main
    pull_request:
        types: [ opened, reopened, synchronize ]

jobs:
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Version Fetcher
                run:  echo "VERSION=$(python setup.py --version)" >> ${GITHUB_ENV}
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: config/release_draft_config.yml
                    name:        lunchmoney
                    tag:         "v$ {{ env.VERSION }}"
                    version:     "$ {{ env.VERSION }}"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
