name: Release Drafter

on:
    push:
        branches:
            - main
    pull_request:
        types: [ opened, reopened, synchronize ]

jobs:
    Release:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Version Fetcher
                run:  |
                      echo PROJECT_VERSION=$(python setup.py --version) >> ${GITHUB_ENV}
                      echo PROJECT_TAG="v$(python setup.py --version)" >> ${GITHUB_ENV}
                      echo PROJECT_RELEASE="$(python setup.py --name) v$(python setup.py --version)" >> ${GITHUB_ENV}
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter.yml
                    name:        ${{ env.PROJECT_RELEASE }}
                    version:     ${{ env.PROJECT_VERSION }}
                    tag:         ${{ env.PROJECT_TAG }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
