name: Release Drafter

on:
    push:
        branches:
            - main
    pull_request:
        types: [ opened, reopened, synchronize ]

jobs:
    Release:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Version Fetcher
                run:  |
                      echo "LUNCHMONEY_VERSION=$(python setup.py --version)" >> ${GITHUB_ENV}
                      echo "LUNCHMONEY_TAG=v${LUNCHMONEY_VERSION}" >> ${GITHUB_ENV}
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter.yml
                    name:        lunchmoney
                    version:     $ {{env.LUNCHMONEY_VERSION }}
                    tag:         $ {{env.LUNCHMONEY_TAG }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
