name: Release Drafter

on:
    push:
        branches:
            - main
    pull_request:
        types: [ opened, reopened, synchronize ]

jobs:
    Release:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Version Fetcher
                run:  |
                      echo PROJECT_NAME=$(python setup.py --name) >> ${GITHUB_ENV}
                      echo PROJECT_VERSION=$(python setup.py --version) >> ${GITHUB_ENV}
            -   name: Draft a Release
                uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter.yml
                    name:        '${{ env.PROJECT_NAME }} ${{ env.PROJECT_TAG }}'
                    version:     ${{ env.PROJECT_VERSION }}
                    tag:         'v${{ env.PROJECT_VERSION }}'
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
