name: Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches: [ "**" ]

jobs:
    test-suite:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { name: 'Python 3.9', python: '3.9', tox: py39 }
                    - { name: 'Python 3.8', python: '3.8', tox: py38 }
                    - { name: 'Python 3.7', python: '3.7', tox: py37 }
                    - { name: 'Python 3.6', python: '3.6', tox: py36 }
        env:
            LUNCHMONEY_ACCESS_TOKEN: ${{ secrets.LUNCHMONEY_ACCESS_TOKEN }}
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python Environment ${{ matrix.python }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python }}
            -   name: Install Test Dependencies
                run:  |
                      python -m pip install --upgrade pip wheel
                      python -m pip install tox
            -   name: Tox Test Suite
                run:  |
                      echo "::add-matcher::.github/matchers/python.json"
                      tox -e ${{ matrix.tox }}
                      echo "::remove-matcher owner=python::"
    docker-ci:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Declare Version Variable
                run:  |
                      VERSION=$(python setup.py --version)
                      echo VERSION=${VERSION} >> ${GITHUB_ENV}
            -   name: Docker Image Building
                uses: docker/build-push-action@v2
                with:
                    load: true
                    push: false
                    tags: juftin/lunchable:latest,juftin/lunchable:${{ env.VERSION }}
            -   name: Test Docker Image
                run:  |
                      docker run --rm juftin/lunchable:latest

    version-checker:
        if:      |
                 ${{ github.event_name == 'pull_request' }} ||
                 ${{ github.base_ref == 'main' }}
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: "3.9"
            -   name: Checkout Main Branch
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    ref:         main
            -   name: Get Main Version
                run:  |
                      MAIN_VERSION="$(python setup.py --version)"
                      echo MAIN_VERSION="${MAIN_VERSION}" >> ${GITHUB_ENV}
            -   name: Checkout Current Ref
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    ref:         ${{ github.ref }}
            -   name: Get Current Version
                run:  |
                      CURRENT_VERSION="$(python setup.py --version)"
                      echo CURRENT_VERSION="${CURRENT_VERSION}" >> ${GITHUB_ENV}
            -   name: Compare Versions
                run:  |
                      pip install packaging
                      python "${{ github.workspace }}/.github/helpers/version_check.py"
            -   name: Compare Versions
                run:  |
                      echo "Current Version: ${CURRENT_VERSION}"
                      echo "Main Version: ${MAIN_VERSION}"
                      echo "Proceeding, version check passed."
