name: Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ "**" ]

jobs:
    test-suite:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { name: 'Python 3.9', python: '3.9', tox: py39 }
                    - { name: 'Python 3.8', python: '3.8', tox: py38 }
                    - { name: 'Python 3.7', python: '3.7', tox: py37 }
                    - { name: 'Python 3.6', python: '3.6', tox: py36 }
                    - { name: 'Python 3.10', python: '3.10', tox: py310 }
        env:
            LUNCHMONEY_ACCESS_TOKEN:   ${{ secrets.LUNCHMONEY_ACCESS_TOKEN }}
            SENSITIVE_REQUEST_STRINGS: ${{ secrets.SENSITIVE_REQUEST_STRINGS }}
            SPLITWISE_CONSUMER_KEY:    ${{ secrets.SPLITWISE_CONSUMER_KEY }}
            SPLITWISE_CONSUMER_SECRET: ${{ secrets.SPLITWISE_CONSUMER_SECRET }}
            SPLITWISE_API_KEY:         ${{ secrets.SPLITWISE_API_KEY }}
            PUSHOVER_USER_KEY:         ${{ secrets.PUSHOVER_USER_KEY }}
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python Environment ${{ matrix.python }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python }}
            -   name: Install Test Dependencies
                run:  |
                      python -m pip install --upgrade pip wheel
                      python -m pip install tox
            -   name: Tox Test Suite
                run:  |
                      echo "::add-matcher::.github/matchers/python.json"
                      tox -e ${{ matrix.tox }}
                      echo "::remove-matcher owner=python::"
    docker-ci:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Declare Version Variable
                run:  |
                      VERSION=$(python setup.py --version)
                      echo VERSION=${VERSION} >> ${GITHUB_ENV}
            -   name: Docker Image Building
                uses: docker/build-push-action@v2
                with:
                    load: true
                    push: false
                    tags: juftin/lunchable:latest,juftin/lunchable:${{ env.VERSION }}
            -   name: Test Docker Image
                run:  |
                      docker run --rm juftin/lunchable:latest
